export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBERS_BASTKET = "GET_NUMBERS_BASTKET";
export const UPDATE_QTY = "UPDATE_QTY";
export const DECREASE_QTY = "DECREASE_QTY";
export const INCREASE_QTY = "INCREASE_QTY";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const COUNTRY_OPTIONS = [
  { value: 1, label: "Hà Nội" },
  { value: 2, label: "Đà Nẵng" },
  { value: 3, label: "TP Hồ Chí Minh" },
  { value: 4, label: "Huế" },
  { value: 5, label: "Đà Lạt" },
  { value: 6, label: "Vũng tàu" },
  { value: 7, label: "Cao Bằng" },
  { value: 8, label: "Cao Lãnh" },
];

export const MONTH_BIRTHDAY_OPTIONS = [
  { value: 1, label: "January" },
  { value: 2, label: "Febuary" },
  { value: 3, label: "March" },
  { value: 4, label: "April" },
  { value: 5, label: "May" },
  { value: 6, label: "June" },
  { value: 7, label: "July" },
  { value: 8, label: "August" },
  { value: 9, label: "September" },
  { value: 10, label: "October" },
  { value: 11, label: "November" },
  { value: 12, label: "December" },
];

export const DAY_BIRTHDAY_OPTIONS = [
  { value: 1, label: "1" },
  { value: 2, label: "2" },
  { value: 3, label: "3" },
  { value: 4, label: "4" },
  { value: 5, label: "5" },
  { value: 6, label: "6" },
  { value: 7, label: "7" },
  { value: 8, label: "8" },
  { value: 9, label: "9" },
  { value: 10, label: "10" },
  { value: 11, label: "11" },
  { value: 12, label: "12" },
  { value: 13, label: "13" },
  { value: 14, label: "14" },
  { value: 15, label: "15" },
  { value: 16, label: "16" },
  { value: 17, label: "17" },
  { value: 18, label: "18" },
  { value: 19, label: "19" },
  { value: 20, label: "20" },
  { value: 21, label: "21" },
  { value: 22, label: "22" },
  { value: 23, label: "23" },
  { value: 24, label: "24" },
  { value: 25, label: "25" },
  { value: 26, label: "26" },
  { value: 27, label: "27" },
  { value: 28, label: "28" },
  { value: 29, label: "29" },
  { value: 30, label: "30" },
  { value: 31, label: "31" },
];

export const YEAR_BIRTHDAY_OPTIONS = [
  { value: 1, label: "1990" },
  { value: 2, label: "1991" },
  { value: 3, label: "1992" },
  { value: 4, label: "1993" },
  { value: 6, label: "1994" },
  { value: 7, label: "1995" },
  { value: 8, label: "1996" },
  { value: 9, label: "1997" },
  { value: 10, label: "1998" },
  { value: 11, label: "1999" },
  { value: 12, label: "2000" },
  { value: 13, label: "2001" },
  { value: 14, label: "2002" },
  { value: 15, label: "2003" },
  { value: 16, label: "2004" },
  { value: 17, label: "2005" },
  { value: 18, label: "2006" },
  { value: 19, label: "2007" },
  { value: 20, label: "2008" },
  { value: 21, label: "2009" },
  { value: 22, label: "2010" },
  { value: 23, label: "2011" },
  { value: 24, label: "2012" },
  { value: 25, label: "2013" },
  { value: 26, label: "2014" },
  { value: 27, label: "2015" },
  { value: 28, label: "2016" },
  { value: 29, label: "2018" },
  { value: 30, label: "2019" },
  { value: 31, label: "2020" },
  { value: 32, label: "2021" },
];
